# Text Classification



## Preprocess

In [1]:
import pandas as pd
import numpy as np
import nltk
from google.colab import drive
from nltk.tokenize import RegexpTokenizer
# KERAS
import tensorflow as tf
from tensorflow import keras
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

In [2]:
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [21]:
df_processed = pd.read_csv('gdrive/MyDrive/save_file/20220218/data_test_processed_formal.csv')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (9) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [22]:
tokenizer_data = RegexpTokenizer(r'\w+')
df_processed['value_tokenize'] = df_processed['review_formal_processed'].map(tokenizer_data.tokenize)

In [ ]:
value = df_processed["value_tokenize"]

In [ ]:
import pickle

with open('gdrive/MyDrive/save_file/20220218/tokenizer.pickle', 'rb') as handle:
    loaded_tokenizer = pickle.load(handle)

In [ ]:
from keras.models import load_model

# load model from single file
model = load_model('gdrive/MyDrive/save_file/20220218/lstm.h5')

In [ ]:
seq = loaded_tokenizer.texts_to_sequences(value)
padded = pad_sequences(seq, padding = 'post')
pred = model.predict(padded)
print(pred)

[[9.99956727e-01 4.32402085e-05 7.46220774e-09 1.12617853e-08]
 [5.73826453e-09 1.18868948e-05 9.99988079e-01 4.81668323e-08]
 [1.00000000e+00 2.78277320e-13 1.07648036e-10 1.16900611e-09]
 ...
 [2.48246209e-07 7.00185637e-07 4.45428304e-06 9.99994636e-01]
 [4.41332986e-06 2.30848840e-07 9.99995232e-01 7.48011288e-08]
 [9.99805033e-01 2.33505343e-05 1.61745584e-06 1.69928899e-04]]


In [ ]:
np.savetxt('pred_test_20220219.csv',pred, delimiter=',')

In [ ]:
act_labels = {0:0, 1:1, 2:2, 3:3}

In [ ]:
act_labels

{0: 0, 1: 1, 2: 2, 3: 3}

In [ ]:
rev_act_labels = {val: key for key, val in act_labels.items()}
predictions = np.argmax(pred, axis=1)
act_predictions  = [rev_act_labels[val] for val in predictions]
print(act_predictions)

[0, 2, 0, 1, 3, 2, 1, 2, 0, 1, 0, 2, 0, 3, 1, 3, 2, 2, 0, 3, 1, 2, 2, 3, 0, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 0, 0, 3, 3, 2, 2, 1, 1, 0, 0, 2, 0, 2, 2, 0, 2, 1, 0, 2, 2, 0, 1, 2, 0, 2, 2, 0, 1, 0, 1, 3, 0, 2, 3, 1, 0, 2, 1, 3, 2, 1, 2, 2, 0, 1, 2, 2, 1, 0, 2, 2, 1, 2, 0, 0, 1, 3, 0, 1, 1, 0, 1, 2, 3, 1, 1, 0, 2, 3, 0, 0, 1, 2, 1, 0, 2, 3, 1, 2, 3, 3, 0, 3, 2, 2, 3, 0, 2, 2, 0, 0, 1, 0, 1, 2, 2, 2, 2, 0, 0, 0, 0, 0, 1, 3, 2, 1, 0, 1, 2, 3, 3, 2, 0, 0, 3, 1, 0, 3, 1, 2, 1, 3, 1, 2, 1, 3, 2, 3, 2, 2, 3, 2, 2, 3, 2, 3, 0, 2, 2, 2, 2, 2, 0, 0, 2, 2, 3, 0, 0, 3, 2, 2, 3, 1, 3, 0, 0, 3, 1, 1, 2, 0, 2, 3, 3, 3, 2, 0, 0, 1, 3, 0, 1, 3, 0, 3, 2, 0, 2, 0, 3, 0, 1, 2, 2, 3, 2, 0, 2, 3, 2, 0, 3, 3, 0, 3, 2, 1, 2, 3, 0, 2, 0, 2, 0, 0, 2, 2, 3, 2, 2, 0, 2, 3, 2, 3, 3, 3, 1, 0, 2, 2, 3, 2, 3, 2, 1, 0, 1, 3, 3, 3, 1, 3, 1, 1, 3, 2, 0, 3, 0, 1, 1, 2, 1, 1, 1, 3, 1, 3, 0, 3, 0, 2, 3, 3, 2, 1, 1, 0, 3, 1, 3, 2, 3, 3, 2, 1, 3, 0, 2, 1, 1, 2, 0, 2, 0, 3, 2, 2, 3, 2, 2, 0, 2, 1, 2, 2, 0, 2, 3, 0, 2, 1, 3, 

In [ ]:
act_predictions

[0,
 2,
 0,
 1,
 3,
 2,
 1,
 2,
 0,
 1,
 0,
 2,
 0,
 3,
 1,
 3,
 2,
 2,
 0,
 3,
 1,
 2,
 2,
 3,
 0,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 2,
 2,
 1,
 2,
 0,
 0,
 3,
 3,
 2,
 2,
 1,
 1,
 0,
 0,
 2,
 0,
 2,
 2,
 0,
 2,
 1,
 0,
 2,
 2,
 0,
 1,
 2,
 0,
 2,
 2,
 0,
 1,
 0,
 1,
 3,
 0,
 2,
 3,
 1,
 0,
 2,
 1,
 3,
 2,
 1,
 2,
 2,
 0,
 1,
 2,
 2,
 1,
 0,
 2,
 2,
 1,
 2,
 0,
 0,
 1,
 3,
 0,
 1,
 1,
 0,
 1,
 2,
 3,
 1,
 1,
 0,
 2,
 3,
 0,
 0,
 1,
 2,
 1,
 0,
 2,
 3,
 1,
 2,
 3,
 3,
 0,
 3,
 2,
 2,
 3,
 0,
 2,
 2,
 0,
 0,
 1,
 0,
 1,
 2,
 2,
 2,
 2,
 0,
 0,
 0,
 0,
 0,
 1,
 3,
 2,
 1,
 0,
 1,
 2,
 3,
 3,
 2,
 0,
 0,
 3,
 1,
 0,
 3,
 1,
 2,
 1,
 3,
 1,
 2,
 1,
 3,
 2,
 3,
 2,
 2,
 3,
 2,
 2,
 3,
 2,
 3,
 0,
 2,
 2,
 2,
 2,
 2,
 0,
 0,
 2,
 2,
 3,
 0,
 0,
 3,
 2,
 2,
 3,
 1,
 3,
 0,
 0,
 3,
 1,
 1,
 2,
 0,
 2,
 3,
 3,
 3,
 2,
 0,
 0,
 1,
 3,
 0,
 1,
 3,
 0,
 3,
 2,
 0,
 2,
 0,
 3,
 0,
 1,
 2,
 2,
 3,
 2,
 0,
 2,
 3,
 2,
 0,
 3,
 3,
 0,
 3,
 2,
 1,
 2,
 3,
 0,
 2,
 0,
 2,
 0,
 0,
 2,
 2,
 3,
 2,
 2,
 0,


In [ ]:
ser = pd.Series(act_predictions)

In [ ]:
ser.shape

(905020,)

In [ ]:
ser.to_csv('label_20220219.csv')

In [30]:
labelled = pd.read_csv('gdrive/MyDrive/save_file/20220219/label_20220219.csv', index_col=0)

In [31]:
labelled.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 905020 entries, 0 to 905019
Data columns (total 1 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   0       905020 non-null  int64
dtypes: int64(1)
memory usage: 13.8 MB


In [34]:
result = pd.concat([df_processed, labelled], axis=1)

In [35]:
result

app_name  ...  0
0                             blibli  ...  0
1                          tokopedia  ...  2
2                               jdid  ...  0
3                          bukalapak  ...  1
4                          tokopedia  ...  3
...                              ...  ... ..
905015                        blibli  ...  1
905016                        shopee  ...  1
905017                        lazada  ...  3
905018  Sambut Tahun Baru di Shopee!  ...  2
905019      Shopee: Belanja di 11.11  ...  0

[905020 rows x 18 columns]

In [39]:
column_name = ["app_name", "app_id", "alt_app_id", "review_id", "user_name", "user_image", "review", "rating", "thumbs_up_count", "app_version", "created_date", "reply", "replied_at", "platform", "review_processed", "review_formal_processed", "value_tokenize", "topic"] 

result.columns = column_name

In [40]:
result.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 905020 entries, 0 to 905019
Data columns (total 18 columns):
 #   Column                   Non-Null Count   Dtype 
---  ------                   --------------   ----- 
 0   app_name                 905020 non-null  object
 1   app_id                   905020 non-null  object
 2   alt_app_id               905020 non-null  object
 3   review_id                905020 non-null  object
 4   user_name                905020 non-null  object
 5   user_image               902084 non-null  object
 6   review                   905020 non-null  object
 7   rating                   905020 non-null  int64 
 8   thumbs_up_count          905020 non-null  int64 
 9   app_version              90260 non-null   object
 10  created_date             905020 non-null  object
 11  reply                    352054 non-null  object
 12  replied_at               905020 non-null  object
 13  platform                 905020 non-null  object
 14  review_processed    

In [41]:
result

app_name  ... topic
0                             blibli  ...     0
1                          tokopedia  ...     2
2                               jdid  ...     0
3                          bukalapak  ...     1
4                          tokopedia  ...     3
...                              ...  ...   ...
905015                        blibli  ...     1
905016                        shopee  ...     1
905017                        lazada  ...     3
905018  Sambut Tahun Baru di Shopee!  ...     2
905019      Shopee: Belanja di 11.11  ...     0

[905020 rows x 18 columns]

In [42]:
result['topic'].value_counts()

0    266205
2    258036
3    216923
1    163856
Name: topic, dtype: int64

In [43]:
result.to_csv('data_test_labelled_20220219.csv',   header=["app_name", "app_id", "alt_app_id", "review_id", "user_name", "user_image", "review", "rating", "thumbs_up_count", "app_version", "created_date", "reply", "replied_at", "platform", "review_processed", "review_formal_processed", "value_tokenize", "topic"], chunksize=100000, index = False, mode='a')